export const TODO_ACTIONS = {
//	Async
	FETCH_START: 'FETCH_START',
	FETCH_SUCCESS: 'FETCH_SUCCESS',
	FETCH_ERROR: 'FETCH_ERROR',
	
//  Todo mutations
	ADD_TODO_START: 'ADD_TODO_START',
	ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
	ADD_TODO_ERROR: 'ADD_TODO_ERROR',
	COMPLETE_TODO_: 'COMPLETE_TODO_',
	UPDATE_TODO_: 'UPDATE_TODO_',

//	UI Operations
	SET_SORT: 'SET_SORT',
	SET_FILTER: 'SET_FILTER',
	CLEAR_ERROR: 'CLEAR_ERROR',
	RESET_FILTERS: 'RESET_FILTERS'
}